toggle-item:
  material: BLAZE_ROD
  name: "&aToggle Players"
  lore:
    - "&7Click to hide/show players"
  glow: true

auto-give:
  enabled: true
  slot: 8

options:
  movable: false
  droppable: false

bossbar:
  enabled: true
  color: "RED"      #possible values: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
  style: "SOLID"    #possible values: SOLID, SEGMENTED_6, SEGMENTED_10, etc.
